baseURL = "https://xionicarus19.github.io/mchilhama/"
languageCode = "id-ID"
title = "Moch. Ilham Abdillah"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Tentang"
    url = "about/"
    weight = 1
  [[menu.main]]
    name = "Proyek"
    url = "projects/"
    weight = 2